import React from 'react';
import { ArrowLeft, ShieldCheck, Activity } from 'lucide-react';
import { PriceTag } from '../../components/shared/PriceTag';
import { RarityBadge } from '../../components/shared/RarityBadge';
import { WalletBadge } from '../../components/shared/WalletBadge';
import { ChartWidget } from '../../components/shared/ChartWidget';
import { nfts } from '../../mock/nfts';
import { useCurrency } from '../../context/CurrencyContext';

export const NFTDetail = () => {
  const nft = nfts[0];
  const { formatPrice } = useCurrency();
  return (
    <div className="pb-24 animate-in fade-in zoom-in duration-300">
      <button className="flex items-center gap-2 text-text-muted hover:text-gray-900 font-bold mb-8 transition-colors group">
        <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" /> Back to Marketplace
      </button>
      
      <div className="flex flex-col lg:flex-row gap-12">
        <div className="w-full lg:w-1/2">
          <div className="aspect-square rounded-[40px] overflow-hidden shadow-2xl ring-4 ring-white/30 relative">
            <img src={nft.coverImage} alt={nft.songTitle} className="w-full h-full object-cover" />
            <div className="absolute inset-0 bg-gradient-to-tr from-white/10 to-transparent pointer-events-none" />
          </div>
        </div>
        
        <div className="flex-1 space-y-8">
          <div>
            <div className="flex items-center gap-3 mb-4">
              <RarityBadge rarity={nft.rarity} />
              <span className="text-text-dim font-bold text-sm tracking-wide uppercase">Edition #{nft.editionNumber} of {nft.totalEditions}</span>
            </div>
            <h1 className="text-4xl font-extrabold text-gray-900 mb-2">{nft.songTitle}</h1>
            <p className="text-xl text-text-dim">by <span className="text-secondary font-bold hover:underline cursor-pointer">{nft.artistName}</span></p>
          </div>

          <div className="glass-card p-8 border border-white/50 bg-white/40">
            <p className="text-sm text-text-muted font-bold uppercase tracking-wider mb-2">Current Price</p>
            <h2 className="text-5xl font-extrabold text-gray-900 mb-8">{formatPrice(nft.price)}</h2>
            
            <div className="flex gap-4">
              <button className="flex-1 py-4 bg-secondary/10 text-secondary border border-secondary/20 font-bold rounded-2xl hover:bg-secondary/20 transition-all text-lg shadow-sm">Buy Now</button>
              <button className="flex-1 py-4 bg-white/50 border-2 border-gray-900 text-gray-900 font-bold rounded-2xl hover:bg-white transition-colors text-lg">Make Offer</button>
            </div>
          </div>

          {nft.priceHistory && (
            <div className="h-80">
              <ChartWidget 
                title="Price History" 
                type="line" 
                data={nft.priceHistory.map(h => h.price)} 
                labels={nft.priceHistory.map(h => h.date)} 
              />
            </div>
          )}

          <div className="space-y-4">
            <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2"><ShieldCheck size={20} className="text-green-600" /> Utility & Perks</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-5 glass-card bg-primary/10 hover:bg-primary/20 transition-colors">
                <h4 className="font-bold text-gray-900 text-sm mb-1">Royalty Share</h4>
                <p className="text-xs text-text-dim leading-relaxed">Earn 5% of streaming revenue generated by this song.</p>
              </div>
              <div className="p-5 glass-card bg-secondary/10 hover:bg-secondary/20 transition-colors">
                <h4 className="font-bold text-gray-900 text-sm mb-1">Exclusive Access</h4>
                <p className="text-xs text-text-dim leading-relaxed">Join the private Discord channel for verified holders.</p>
              </div>
            </div>
          </div>

          <div>
            <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2 mb-4"><Activity size={20} className="text-text-muted" /> History</h3>
            <div className="space-y-3">
              {[1, 2, 3].map(i => (
                <div key={i} className="flex items-center justify-between p-4 glass-card hover:bg-white/50 transition-colors">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-secondary/10 flex items-center justify-center text-xs font-bold text-secondary">Tx</div>
                    <div>
                      <p className="font-bold text-gray-900 text-sm">Purchased by <span className="text-secondary font-mono">0x71...976F</span></p>
                      <p className="text-xs text-text-muted">2 hours ago</p>
                    </div>
                  </div>
                  <div className="font-bold text-gray-900">{formatPrice(nft.price)}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
